steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llminsurance-backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llminsurance-backend:latest'
      - '.'
    id: 'build-image'

  # 2. 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/llminsurance-backend:$BUILD_ID'
    id: 'push-image'
    waitFor: ['build-image']

  # 3. Cloud Run에 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'llminsurance-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/llminsurance-backend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod'
      - '--set-env-vars'
      - 'DATABASE_URL=jdbc:postgresql://google/${_DATABASE_NAME}?cloudSqlInstance=${_CLOUDSQL_INSTANCE_CONNECTION}&socketFactory=com.google.cloud.sql.postgres.SocketFactory'
      - '--set-env-vars'
      - 'DATABASE_USERNAME=${_DATABASE_USERNAME}'
      - '--set-env-vars'
      - 'DATABASE_PASSWORD=${_DATABASE_PASSWORD}'
      - '--set-env-vars'
      - 'JWT_SECRET=${_JWT_SECRET}'
      - '--set-env-vars'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
    id: 'deploy-cloudrun'
    waitFor: ['push-image']

# 이미지 저장
images:
  - 'gcr.io/$PROJECT_ID/llminsurance-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/llminsurance-backend:latest'

# 빌드 설정
options:
  machineType: 'E2_STANDARD_2'
  diskSizeGb: '20'

# 환경 변수 대체 (Cloud Build 트리거에서 설정)
substitutions:
  _DATABASE_NAME: 'llminsurance'
  _DATABASE_USERNAME: 'llminsurance_user'
  # 보안 정보는 Cloud Build 콘솔에서 환경변수로 설정
  # _DATABASE_PASSWORD: 설정 필요
  _CLOUDSQL_INSTANCE_CONNECTION: 'my-first-project:us-central1:llminsurance-postgres'
  # _JWT_SECRET: 설정 필요
  # _OPENAI_API_KEY: 설정 필요

# 빌드 타임아웃
timeout: '1200s' 